### ISSUE TITLE
envsubst: command not found

### ISSUE THREAD

**Issue by kathanesamyak** [aws-samples/dr-with-eks-efs#1]
[$ envsubst < config_files/pri_region_eksctl_template.yaml | eksctl create cluster -f -](url)

When i run above, i get below error-
```
-bash: envsubst: command not found
Error: loading config file "-": Object 'Kind' is missing in ''

```
You may want to first install gettext. Pleaes add a note in the repo to install it-
`sudo yum install -y gettext`

**Comment by dumlutimuralp** [comment]
Fixed.
